name: 🧪 CI

on:
 workflow_dispatch:
 
 push:
   branches:
   - main

env:
  NAME: Liam Neville
  FORMAT: SINGLES
  GENDER: M
  LEVEL: "4.0"
  SECTION: New England

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v10
        with:
          command: config
          globs: |
            config/.markdownlint.jsonc
            **/*.md
          
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: 🧪 Test
        run: |
          dotnet test

      
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        working-directory: ${{ github.workspace }}
        run: docker build -t usta-cli .
      
      - name: Run
        run: |
          echo 'EMAIL_BODY<<EOF' >> $GITHUB_ENV
          docker run usta-cli rankings get -n '${{ env.NAME }}' -f '${{ env.FORMAT }}' -g '${{ env.GENDER }}' -l '${{ env.LEVEL }}' -s '${{ env.SECTION }}' -o html >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "$EMAIL_BODY" >> $GITHUB_STEP_SUMMARY
