name: 🧪 CI

on:
 workflow_dispatch:
 
 push:
   branches:
   - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v10
        with:
          command: config
          globs: config/.markdownlint-cli2.jsonc '**/*.md'
          
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: 🧪 Test
        run: |
          dotnet test
