name: 🧪 CI

on:
  workflow_dispatch:

  push:
    branches:
      - main

env:
  NAME: Liam Neville
  FORMAT: SINGLES
  GENDER: M
  LEVEL: "4.0"
  SECTION: New England
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Build
        working-directory: ${{ github.workspace }}
        run: docker build -t usta-cli .

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v10
        with:
          command: config
          globs: |
            config/.markdownlint.jsonc
            **/*.md

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: 🧪 Test
        run: |
          dotnet test

  multi-platform-run:
    runs-on: ${{ matrix.os }}
    needs: test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - if: matrix.os == 'macos-latest'
        name: Setup Docker on macOS
        uses: douglascamata/setup-docker-macos-action@v1-alpha

      - uses: docker/build-push-action@v5
        with:
          tags: test-image:latest
          push: false

      - uses: addnab/docker-run-action@v3
        with:
          image: test-image:latest
          run: |
            echo 'EMAIL_BODY<<EOF' >> $GITHUB_ENV
            docker run test-image:latest rankings get -n '${{ env.NAME }}' -f '${{ env.FORMAT }}' -g '${{ env.GENDER }}' -l '${{ env.LEVEL }}' -s '${{ env.SECTION }}' -o html >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV
