name: Build Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        working-directory: ${{ github.workspace }}
        run: docker build -t usta-scraper .
      - name: Run the Docker image
        run: |
          docker run -t --rm usta-scraper -n 'Liam Neville' -f SINGLES -g M -l level_4_0 -s 'Northern California' >> $GITHUB_STEP_SUMMARY
