name: Build Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        working-directory: ${{ github.workspace }}
        run: docker build -f '${{ github.workspace }}/Dockerfile' -t usta-scraper .
      - name: Run the Docker image
        run: |
          docker run -t usta-scraper -- --name 'Liam Neville' \
            --format SINGLES \
            --gender M \
            --level level_4_0 \
            --section 'Northern California' >> $GITHUB_STEP_SUMMARY
