name: Build Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        working-directory: ${{ github.workspace }}
        run: docker build -t usta-scraper .
      - name: Run the Docker image
        run: |
          docker run -t --rm -e 'NTRP_NAME=Liam Neville' -e 'NTRP_FORMAT=SINGLES' -e 'NTRP_GENDER=M' -e 'NTRP_LEVEL=level_4_0' -e 'NTRP_SECTION=Northern California' usta-scraper >> $GITHUB_STEP_SUMMARY
